doc: add changelog, fix typos
simatic-ax/template-app pull request #37
Opened 2024-06-21 15:01 UTC by BeckerStS

2024-06-21 16:55 UTC, sjuergen requested changes

2024-06-21 16:55 UTC, sjuergen commented on CHANGELOG.md
Changelog is not required

2024-06-21 16:55 UTC, sjuergen commented on CHANGELOG.md
Changelog is not required

2024-06-21 16:55 UTC, sjuergen commented on template/CHANGELOG.md
Changelog is not required. This will be created during the release

2024-06-21 17:08 UTC, sjuergen requested changes
Changelog are not required. Will be generated.

2024-06-26 20:36 UTC, BeckerStS commented on CHANGELOG.md
agree

2024-06-26 20:36 UTC, BeckerStS commented on template/CHANGELOG.md
agree

2024-06-26 20:38 UTC, BeckerStS commented on CHANGELOG.md
agree

2024-06-26 20:53 UTC, BeckerStS commented
new commit includes the changes ... pls double-check and merge @sjuergen

2025-02-03 18:30 UTC, merged